# fly.toml app configuration file generated for simple-websocket-rooms on 2023-12-08T16:30:22+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "simple-websocket-rooms"
primary_region = "otp"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[http_service.tls_options]
  alpn = ["h2", "http/1.1"]
  versions = ["TLSv1.2", "TLSv1.3"]
  default_self_signed = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
